name: AukiStandardProtocolsIOS

options:
  bundleIdPrefix: com.aukilabs.examples
  deploymentTarget:
    iOS: "17.0"

packages:
  AukiSDK:
    path: ../../../bindings/swift/auki-sdk-swift
  AukiStandardPlayground:
    path: Package

targets:
  AukiStandardProtocolsIOS:
    type: application
    platform: iOS
    sources:
      - App
    dependencies:
      - package: AukiSDK
        product: AukiSDK
      - package: AukiStandardPlayground
        product: AukiStandardPlayground
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aukilabs.examples.StandardProtocols
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        SWIFT_VERSION: "6.0"
        TARGETED_DEVICE_FAMILY: "1,2"

  AukiStandardProtocolsIOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    dependencies:
      - target: AukiStandardProtocolsIOS
      - package: AukiSDK
        product: AukiSDK
      - package: AukiStandardPlayground
        product: AukiStandardPlayground
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aukilabs.examples.StandardProtocolsTests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "6.0"

schemes:
  AukiStandardProtocolsIOS:
    build:
      targets:
        AukiStandardProtocolsIOS: all
        AukiStandardProtocolsIOSTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - AukiStandardProtocolsIOSTests
