[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "auki-uniffi-test"
version = "0.0.0"
description = "UniFFI-generated Python bindings for auki-uniffi-test."
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Auki Labs Limited" }]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: Implementation :: CPython",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
Repository = "https://github.com/aukilabs/auki-sdk"

[tool.setuptools]
packages = ["auki_uniffi_test"]

[tool.setuptools.package-data]
auki_uniffi_test = ["native/*/*"]
