[workspace]
resolver = "2"
members = [
    "crates/auki-hash",
    "crates/auki-geometry",
    "crates/auki-maps",
    "crates/auki-mappers",
    "bindings/python/auki-geometry-py",
    "crates/auki-identity",
    "bindings/python/auki-identity-py",
    "crates/auki-jcs",
    "crates/auki-logs",
    "bindings/python/auki-logs-py",
    "crates/auki-manifests",
    "bindings/python/auki-manifests-py",
    "crates/auki-network",
    "crates/auki-domain-relay",
    "crates/auki-network-browser-wasm",
    "bindings/python/auki-network-py",
    "bindings/swift/auki-network-swift",
    "bindings/swift/auki-identity-swift",
    "crates/auki-datatypes",
    "crates/auki-domain",
    "bindings/python/auki-domain-py",
    "crates/auki-registry",
    "bindings/python/auki-registry-py",
    "crates/auki-ros-adapter",
    "crates/auki-layout",
    "bindings/python/auki-layout-py",
    "crates/auki-session",
    "bindings/python/auki-session-py",
    "crates/auki-time",
    "examples/diagnostic-app",
]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/aukilabs/auki-sdk"
authors = ["Auki Labs Limited"]
version = "0.0.1"
