# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: audio.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class AudioLogEntry(betterproto.Message):
    data: bytes = betterproto.bytes_field(1)
