# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: camera.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class DynamicIntrinsics(betterproto.Message):
    fx: float = betterproto.double_field(1)
    fy: float = betterproto.double_field(2)
    cx: float = betterproto.double_field(3)
    cy: float = betterproto.double_field(4)
    distortion_coefficients: List[float] = betterproto.double_field(5)


@dataclass
class PinholeCameraLogEntry(betterproto.Message):
    dynamic_intrinsics: "DynamicIntrinsics" = betterproto.message_field(1)
    frame: bytes = betterproto.bytes_field(2)
