# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: frame_stream.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class JpegFrame(betterproto.Message):
    bytes: bytes = betterproto.bytes_field(1)
