# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: joint_encoders_stream.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class JointEncodersFrame(betterproto.Message):
    # Joint angle readings in radians, indexed in the producer's emit order.
    # Length MUST equal the registry entry's `joint_count`.
    angles_rad: List[float] = betterproto.float_field(1)
