# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: point_cloud.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PointCloudFrame(betterproto.Message):
    point_count: int = betterproto.uint32_field(1)
    data: bytes = betterproto.bytes_field(2)
