# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: pose.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SpatialTransform(betterproto.Message):
    translation: "Vec3" = betterproto.message_field(1)
    orientation: "Quat" = betterproto.message_field(2)


@dataclass
class Vec3(betterproto.Message):
    """
    3-component vector, typically meters in the from→to convention described by
    the manifest's `from_frame_hash` / `to_frame_hash` FrameRegistry entries.
    """

    x: float = betterproto.double_field(1)
    y: float = betterproto.double_field(2)
    z: float = betterproto.double_field(3)


@dataclass
class Quat(betterproto.Message):
    """
    Unit quaternion in `(x, y, z, w)` order — Hamilton convention, matching ROS
    `geometry_msgs/Quaternion`. Producers SHOULD normalize before writing;
    consumers SHOULD tolerate small drift from unit length without
    renormalizing silently.
    """

    x: float = betterproto.double_field(1)
    y: float = betterproto.double_field(2)
    z: float = betterproto.double_field(3)
    w: float = betterproto.double_field(4)
