# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: stream.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class StreamRequest(betterproto.Message):
    sensor_id: str = betterproto.string_field(1)


@dataclass
class StreamDescriptor(betterproto.Message):
    sensor_id: str = betterproto.string_field(1)
    sensor_hash: str = betterproto.string_field(2)
    clock_id: str = betterproto.string_field(3)
    clock_hash: str = betterproto.string_field(4)
    frame_id: str = betterproto.string_field(5)
    frame_hash: str = betterproto.string_field(6)


@dataclass
class DeclineReason(betterproto.Message):
    sensor_not_found: "DeclineReasonSensorNotFound" = betterproto.message_field(
        1, group="kind"
    )
    sensor_unavailable: "DeclineReasonSensorUnavailable" = betterproto.message_field(
        2, group="kind"
    )
    producer_shutting_down: "DeclineReasonProducerShuttingDown" = (
        betterproto.message_field(3, group="kind")
    )
    other: "DeclineReasonOther" = betterproto.message_field(4, group="kind")


@dataclass
class DeclineReasonSensorNotFound(betterproto.Message):
    pass


@dataclass
class DeclineReasonSensorUnavailable(betterproto.Message):
    pass


@dataclass
class DeclineReasonProducerShuttingDown(betterproto.Message):
    pass


@dataclass
class DeclineReasonOther(betterproto.Message):
    detail: str = betterproto.string_field(1)


@dataclass
class EndReason(betterproto.Message):
    source_ended: "EndReasonSourceEnded" = betterproto.message_field(1, group="kind")
    producer_shutting_down: "EndReasonProducerShuttingDown" = betterproto.message_field(
        2, group="kind"
    )
    session_ended: "EndReasonSessionEnded" = betterproto.message_field(3, group="kind")
    producer_error: "EndReasonProducerError" = betterproto.message_field(
        4, group="kind"
    )


@dataclass
class EndReasonSourceEnded(betterproto.Message):
    pass


@dataclass
class EndReasonProducerShuttingDown(betterproto.Message):
    pass


@dataclass
class EndReasonSessionEnded(betterproto.Message):
    pass


@dataclass
class EndReasonProducerError(betterproto.Message):
    detail: str = betterproto.string_field(1)


@dataclass
class Frame(betterproto.Message):
    timestamp_ns: int = betterproto.int64_field(1)
    seq: int = betterproto.uint64_field(2)
    payload: bytes = betterproto.bytes_field(3)


@dataclass
class StreamMessage(betterproto.Message):
    request: "StreamRequest" = betterproto.message_field(1, group="variant")
    accept: "StreamDescriptor" = betterproto.message_field(2, group="variant")
    decline: "DeclineReason" = betterproto.message_field(3, group="variant")
    frame: "Frame" = betterproto.message_field(4, group="variant")
    end_of_stream: "EndReason" = betterproto.message_field(5, group="variant")
