# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: time_transform.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class TimeTransformEntry(betterproto.Message):
    # `to_clock - from_clock` at the sample instant, in nanoseconds. Signed
    # because clocks can drift either direction.
    offset_ns: int = betterproto.int64_field(1)
    # Window during which the to-clock was read, expressed in from-clock
    # nanoseconds (`m2 - m1` from the three-read protocol). Sub-microsecond on a
    # healthy host; >1ms suggests system pressure.
    uncertainty_ns: int = betterproto.uint32_field(2)
