import { useEffect, useMemo, useState } from "react";

import { Directory } from "./components/Directory";
import { PeerDetail } from "./components/PeerDetail";
import { QuickSearch } from "./components/QuickSearch";
import { Stage, type StageTileSpec } from "./components/Stage";
import type { OverwatchPeer, PeerSnapshot, SensorSummary } from "./sdk/contract";
import { createOverwatchPeer } from "./sdk/createOverwatchPeer";
import { deriveOperatorState, shortPeerId } from "./state/appState";

const defaultDiscoveryUrl = "http://127.0.0.1:8091";
const defaultDomainName = "overwatch";
const localSensors: SensorSummary[] = [
  {
    sensor_id: "overwatch/browser/generated-bytes",
    sensor_hash: "overwatch-generated-bytes",
    kind: "detection",
    label: "Generated bytes",
  },
];

export function App() {
  const [discoveryUrl, setDiscoveryUrl] = useState(defaultDiscoveryUrl);
  const [domainName, setDomainName] = useState(defaultDomainName);
  const [peer, setPeer] = useState<OverwatchPeer | null>(null);
  const [snapshot, setSnapshot] = useState<PeerSnapshot | null>(null);
  const [status, setStatus] = useState<"idle" | "joining" | "joined" | "error">("idle");
  const [error, setError] = useState<string | null>(null);
  const [selectedPeerId, setSelectedPeerId] = useState<string | null>(null);
  const [tiles, setTiles] = useState<StageTileSpec[]>([]);
  const operatorState = useMemo(() => deriveOperatorState(snapshot), [snapshot]);
  const selectedParticipant = useMemo(() => {
    const participants = snapshot?.participants ?? [];
    return (
      participants.find((participant) => participant.peer_id === selectedPeerId) ??
      operatorState.self ??
      null
    );
  }, [operatorState.self, selectedPeerId, snapshot]);

  useEffect(() => {
    const target = globalThis as typeof globalThis & {
      __overwatch?: {
        snapshot(): PeerSnapshot | null;
        peerId(): string | null;
        subscribeToSensor(peerId: string, sensorId: string): Promise<unknown>;
      };
    };
    target.__overwatch = {
      snapshot: () => snapshot,
      peerId: () => peer?.peerId ?? snapshot?.selfPeerId ?? null,
      subscribeToSensor: async (peerId: string, sensorId: string) => {
        if (!peer) {
          throw new Error("Overwatch peer is not initialized");
        }
        const stream = await peer.subscribeToSensor(peerId, sensorId);
        return readFirstStreamEntry(stream);
      },
    };
    return () => {
      if (target.__overwatch?.snapshot() === snapshot) {
        delete target.__overwatch;
      }
    };
  }, [peer, snapshot]);

  async function joinDomain() {
    setStatus("joining");
    setError(null);
    try {
      const activePeer = peer ?? (await createOverwatchPeer());
      if (!peer) {
        setPeer(activePeer);
      }
      activePeer.observeParticipants(setSnapshot);
      await activePeer.declareSensors(localSensors);
      await activePeer.publishSensor(localSensors[0].sensor_id, {
        kind: "generated-bytes",
        frames: [
          [1, 2, 3, 4],
          [5, 6, 7, 8],
        ],
        interval_ms: 250,
      });
      await activePeer.createOrJoin({ discoveryUrl, clusterName: domainName });
      setStatus("joined");
      setSelectedPeerId((current) => current ?? activePeer.peerId);
    } catch (reason) {
      setStatus("error");
      setError(reason instanceof Error ? reason.message : String(reason));
    }
  }

  async function toggleSensor(
    participant: PeerSnapshot["participants"][number],
    sensor: SensorSummary,
    enabled: boolean,
  ) {
    const tile: StageTileSpec = {
      kind: sensor.kind,
      peerId: participant.peer_id,
      sensorId: sensor.sensor_id,
    };
    if (!enabled) {
      setTiles((current) => current.filter((candidate) => !sameTile(candidate, tile)));
      return;
    }
    setTiles((current) => (current.some((candidate) => sameTile(candidate, tile)) ? current : [...current, tile]));
    if (!participant.is_self && peer) {
      try {
        const stream = await peer.subscribeToSensor(participant.peer_id, sensor.sensor_id);
        const message = await readFirstStreamEntry(stream);
        setTiles((current) =>
          current.map((candidate) => (sameTile(candidate, tile) ? { ...candidate, latestMessage: message } : candidate)),
        );
      } catch (reason) {
        setError(reason instanceof Error ? reason.message : String(reason));
      }
    }
  }

  return (
    <main className="min-h-screen bg-ink text-slate-100">
      <header role="banner" className="border-b border-line bg-ink/95">
        <div className="mx-auto flex max-w-7xl flex-col gap-3 px-4 py-4 md:flex-row md:items-center md:justify-between">
          <div className="min-w-0">
            <p className="text-xs uppercase text-slate-400">Auki Overwatch</p>
            <h1 className="truncate text-xl font-semibold text-white">Browser Domain peer</h1>
          </div>
          <div className="flex flex-wrap items-center gap-2 text-xs">
            <StatusChip label="Domain" value={snapshot?.domainName ?? domainName} />
            <StatusChip label="Peer" value={shortPeerId(peer?.peerId ?? snapshot?.selfPeerId)} />
            <span className={statusClass(status)}>{status}</span>
          </div>
        </div>
      </header>

      <section className="mx-auto grid max-w-7xl gap-4 px-4 py-4 lg:grid-cols-[360px_minmax(0,1fr)]">
        <aside className="grid content-start gap-4">
          <form
            className="rounded-control border border-line bg-panel p-4 shadow-xl shadow-black/20"
            onSubmit={(event) => {
              event.preventDefault();
              void joinDomain();
            }}
          >
            <div className="grid gap-3">
              <label className="grid gap-1 text-sm text-slate-300">
                Discovery URL
                <input
                  className="rounded-control border border-line bg-ink px-3 py-2 text-sm text-white outline-none focus:border-signal"
                  value={discoveryUrl}
                  onChange={(event) => setDiscoveryUrl(event.target.value)}
                />
              </label>
              <label className="grid gap-1 text-sm text-slate-300">
                Domain name
                <input
                  className="rounded-control border border-line bg-ink px-3 py-2 text-sm text-white outline-none focus:border-signal"
                  value={domainName}
                  onChange={(event) => setDomainName(event.target.value)}
                />
              </label>
              <button
                className="rounded-control border border-signal bg-signal px-3 py-2 text-sm font-semibold text-ink disabled:cursor-not-allowed disabled:opacity-60"
                disabled={status === "joining"}
                type="submit"
              >
                {status === "joining" ? "Joining..." : "Join domain"}
              </button>
            </div>
          </form>

          <Directory snapshot={snapshot} selectedPeerId={selectedPeerId} onSelectPeer={setSelectedPeerId} />
        </aside>

        <section className="grid content-start gap-4">
          {error ? (
            <div className="rounded-control border border-red-900/70 bg-red-950/40 p-3 text-sm text-red-100">
              {error}
            </div>
          ) : null}
          <PeerDetail participant={selectedParticipant} onToggleSensor={toggleSensor} />
          <Stage
            tiles={tiles}
            onCloseTile={(tile) => {
              setTiles((current) => current.filter((candidate) => !sameTile(candidate, tile)));
            }}
          />
        </section>
      </section>
      <QuickSearch snapshot={snapshot} onSelectPeer={setSelectedPeerId} />
    </main>
  );
}

async function readFirstStreamEntry(stream: { nextMessage(): Promise<unknown> }): Promise<unknown> {
  let lastMessage: unknown = null;
  for (let i = 0; i < 4; i += 1) {
    const message = await stream.nextMessage();
    lastMessage = message;
    if (
      typeof message === "object" &&
      message !== null &&
      "entry" in message
    ) {
      return message;
    }
  }
  return lastMessage;
}

function StatusChip({ label, value }: { label: string; value: string }) {
  return (
    <span className="rounded-control border border-line bg-panel px-2 py-1 text-slate-300">
      {label}: <span className="font-mono text-slate-100">{value}</span>
    </span>
  );
}

function statusClass(status: "idle" | "joining" | "joined" | "error"): string {
  const base = "rounded-control border px-2 py-1";
  if (status === "joined") {
    return `${base} border-emerald-800 bg-emerald-950/40 text-emerald-200`;
  }
  if (status === "error") {
    return `${base} border-red-900 bg-red-950/40 text-red-200`;
  }
  if (status === "joining") {
    return `${base} border-amber-800 bg-amber-950/40 text-amber-200`;
  }
  return `${base} border-line bg-panel text-slate-300`;
}

function sameTile(a: StageTileSpec, b: StageTileSpec): boolean {
  return a.peerId === b.peerId && a.sensorId === b.sensorId;
}
