import { useEffect, useMemo, useRef, useState } from "react";

import { Directory } from "./components/Directory";
import { PeerDetail } from "./components/PeerDetail";
import { QuickSearch } from "./components/QuickSearch";
import { Stage, type StageTileSpec } from "./components/Stage";
import { startWebcamJpegSource, type WebcamJpegSourceHandle } from "./media/cameraSource";
import type { OverwatchPeer, PeerSnapshot, SensorSummary, StreamHandle } from "./sdk/contract";
import { createOverwatchPeer } from "./sdk/createOverwatchPeer";
import { deriveOperatorState, shortPeerId } from "./state/appState";

const localDiscoveryUrl = "http://127.0.0.1:8091";
const defaultDomainName = "overwatch";
const generatedBytesSensor: SensorSummary = {
  sensor_id: "overwatch/browser/generated-bytes",
  sensor_hash: "overwatch-generated-bytes",
  kind: "detection",
  label: "Generated bytes",
};
const webcamSensor: SensorSummary = {
  sensor_id: "overwatch/browser/webcam-jpeg",
  sensor_hash: "overwatch-webcam-jpeg",
  kind: "camera",
  label: "Webcam",
};
const localSensors: SensorSummary[] = [generatedBytesSensor, webcamSensor];

type TileSubscription = {
  cancelled: boolean;
  stream: StreamHandle | null;
};

export function App() {
  const [discoveryUrl, setDiscoveryUrl] = useState(() => defaultDiscoveryUrlForProtocol(globalThis.location?.protocol));
  const [domainName, setDomainName] = useState(defaultDomainName);
  const [peer, setPeer] = useState<OverwatchPeer | null>(null);
  const [snapshot, setSnapshot] = useState<PeerSnapshot | null>(null);
  const [status, setStatus] = useState<"idle" | "joining" | "joined" | "error">("idle");
  const [error, setError] = useState<string | null>(null);
  const [selectedPeerId, setSelectedPeerId] = useState<string | null>(null);
  const [tiles, setTiles] = useState<StageTileSpec[]>([]);
  const [cameraHandle, setCameraHandle] = useState<WebcamJpegSourceHandle | null>(null);
  const [cameraStatus, setCameraStatus] = useState<"idle" | "starting" | "live" | "error">("idle");
  const [cameraError, setCameraError] = useState<string | null>(null);
  const subscriptionsRef = useRef<Map<string, TileSubscription>>(new Map());
  const operatorState = useMemo(() => deriveOperatorState(snapshot), [snapshot]);
  const selectedParticipant = useMemo(() => {
    const participants = snapshot?.participants ?? [];
    return (
      participants.find((participant) => participant.peer_id === selectedPeerId) ??
      operatorState.self ??
      null
    );
  }, [operatorState.self, selectedPeerId, snapshot]);

  useEffect(() => {
    const target = globalThis as typeof globalThis & {
      __overwatch?: {
        snapshot(): PeerSnapshot | null;
        peerId(): string | null;
        subscribeToSensor(peerId: string, sensorId: string): Promise<unknown>;
      };
    };
    target.__overwatch = {
      snapshot: () => snapshot,
      peerId: () => peer?.peerId ?? snapshot?.selfPeerId ?? null,
      subscribeToSensor: async (peerId: string, sensorId: string) => {
        if (!peer) {
          throw new Error("Overwatch peer is not initialized");
        }
        const stream = await peer.subscribeToSensor(peerId, sensorId);
        return readNextStreamEntry(stream);
      },
    };
    return () => {
      if (target.__overwatch?.snapshot() === snapshot) {
        delete target.__overwatch;
      }
    };
  }, [peer, snapshot]);

  useEffect(() => {
    return () => {
      cameraHandle?.stop();
    };
  }, [cameraHandle]);

  useEffect(() => {
    return () => {
      stopAllSubscriptions(subscriptionsRef.current);
    };
  }, []);

  async function joinDomain() {
    setStatus("joining");
    setError(null);
    try {
      const activePeer = peer ?? (await createOverwatchPeer());
      if (!peer) {
        setPeer(activePeer);
      }
      activePeer.observeParticipants(setSnapshot);
      await activePeer.declareSensors(localSensors);
      await activePeer.publishSensor(generatedBytesSensor.sensor_id, {
        kind: "generated-bytes",
        frames: [
          [1, 2, 3, 4],
          [5, 6, 7, 8],
        ],
        interval_ms: 250,
      });
      await activePeer.createOrJoin({ discoveryUrl, clusterName: domainName });
      setStatus("joined");
      setSelectedPeerId((current) => current ?? activePeer.peerId);
    } catch (reason) {
      setStatus("error");
      setError(reason instanceof Error ? reason.message : String(reason));
    }
  }

  async function toggleCameraCapture() {
    if (cameraHandle != null) {
      cameraHandle.stop();
      setCameraHandle(null);
      setCameraStatus("idle");
      setCameraError(null);
      return;
    }
    if (!peer) {
      setCameraStatus("error");
      setCameraError("Join a domain before starting the webcam");
      return;
    }

    setCameraStatus("starting");
    setCameraError(null);
    let handle: WebcamJpegSourceHandle | null = null;
    try {
      handle = await startWebcamJpegSource();
      await peer.publishSensor(webcamSensor.sensor_id, handle.source);
      setCameraHandle(handle);
      setCameraStatus("live");
    } catch (reason) {
      handle?.stop();
      setCameraStatus("error");
      setCameraError(reason instanceof Error ? reason.message : String(reason));
    }
  }

  async function toggleSensor(
    participant: PeerSnapshot["participants"][number],
    sensor: SensorSummary,
    enabled: boolean,
  ) {
    const tile: StageTileSpec = {
      kind: sensor.kind,
      peerId: participant.peer_id,
      sensorId: sensor.sensor_id,
    };
    if (!enabled) {
      stopTileSubscription(subscriptionsRef.current, tile);
      setTiles((current) => current.filter((candidate) => !sameTile(candidate, tile)));
      return;
    }
    setTiles((current) => (current.some((candidate) => sameTile(candidate, tile)) ? current : [...current, tile]));
    if (!participant.is_self && peer) {
      void readTileSubscription(peer, participant.peer_id, sensor.sensor_id, tile);
    }
  }

  async function readTileSubscription(
    activePeer: OverwatchPeer,
    peerId: string,
    sensorId: string,
    tile: StageTileSpec,
  ) {
    const key = tileKey(tile);
    if (subscriptionsRef.current.has(key)) {
      return;
    }
    const subscription: TileSubscription = { cancelled: false, stream: null };
    subscriptionsRef.current.set(key, subscription);

    try {
      const stream = await activePeer.subscribeToSensor(peerId, sensorId);
      subscription.stream = stream;
      if (subscription.cancelled) {
        void stream.close?.();
        return;
      }
      while (!subscription.cancelled) {
        const message = await readNextStreamEntry(stream);
        if (subscription.cancelled || message == null) {
          break;
        }
        setTiles((current) =>
          current.map((candidate) => (sameTile(candidate, tile) ? { ...candidate, latestMessage: message } : candidate)),
        );
      }
    } catch (reason) {
      if (!subscription.cancelled) {
        setError(reason instanceof Error ? reason.message : String(reason));
      }
    } finally {
      if (subscriptionsRef.current.get(key) === subscription) {
        subscriptionsRef.current.delete(key);
      }
    }
  }

  return (
    <main className="min-h-screen bg-ink text-slate-100">
      <header role="banner" className="border-b border-line bg-ink/95">
        <div className="mx-auto flex max-w-7xl flex-col gap-3 px-4 py-4 md:flex-row md:items-center md:justify-between">
          <div className="min-w-0">
            <p className="text-xs uppercase text-slate-400">Auki Overwatch</p>
            <h1 className="truncate text-xl font-semibold text-white">Browser Domain peer</h1>
          </div>
          <div className="flex flex-wrap items-center gap-2 text-xs">
            <StatusChip label="Domain" value={snapshot?.domainName ?? domainName} />
            <StatusChip label="Peer" value={shortPeerId(peer?.peerId ?? snapshot?.selfPeerId)} />
            <span className={statusClass(status)}>{status}</span>
          </div>
        </div>
      </header>

      <section className="mx-auto grid max-w-7xl gap-4 px-4 py-4 lg:grid-cols-[360px_minmax(0,1fr)]">
        <aside className="grid content-start gap-4">
          <form
            className="rounded-control border border-line bg-panel p-4 shadow-xl shadow-black/20"
            onSubmit={(event) => {
              event.preventDefault();
              void joinDomain();
            }}
          >
            <div className="grid gap-3">
              <label className="grid gap-1 text-sm text-slate-300">
                Discovery URL
                <input
                  className="rounded-control border border-line bg-ink px-3 py-2 text-sm text-white outline-none focus:border-signal"
                  value={discoveryUrl}
                  onChange={(event) => setDiscoveryUrl(event.target.value)}
                />
              </label>
              <label className="grid gap-1 text-sm text-slate-300">
                Domain name
                <input
                  className="rounded-control border border-line bg-ink px-3 py-2 text-sm text-white outline-none focus:border-signal"
                  value={domainName}
                  onChange={(event) => setDomainName(event.target.value)}
                />
              </label>
              <button
                className="rounded-control border border-signal bg-signal px-3 py-2 text-sm font-semibold text-ink disabled:cursor-not-allowed disabled:opacity-60"
                disabled={status === "joining"}
                type="submit"
              >
                {status === "joining" ? "Joining..." : "Join domain"}
              </button>
              <button
                className="rounded-control border border-line bg-ink px-3 py-2 text-sm font-semibold text-slate-100 disabled:cursor-not-allowed disabled:opacity-60"
                disabled={status !== "joined" || cameraStatus === "starting"}
                onClick={() => void toggleCameraCapture()}
                type="button"
              >
                {cameraStatus === "starting"
                  ? "Starting webcam..."
                  : cameraHandle != null
                    ? "Stop webcam"
                    : "Start webcam"}
              </button>
              {cameraError ? <p className="text-xs text-red-200">{cameraError}</p> : null}
            </div>
          </form>

          <Directory snapshot={snapshot} selectedPeerId={selectedPeerId} onSelectPeer={setSelectedPeerId} />
        </aside>

        <section className="grid content-start gap-4">
          {error ? (
            <div className="rounded-control border border-red-900/70 bg-red-950/40 p-3 text-sm text-red-100">
              {error}
            </div>
          ) : null}
          <PeerDetail participant={selectedParticipant} onToggleSensor={toggleSensor} />
          <Stage
            tiles={tiles}
            onCloseTile={(tile) => {
              stopTileSubscription(subscriptionsRef.current, tile);
              setTiles((current) => current.filter((candidate) => !sameTile(candidate, tile)));
            }}
          />
        </section>
      </section>
      <QuickSearch snapshot={snapshot} onSelectPeer={setSelectedPeerId} />
    </main>
  );
}

export function defaultDiscoveryUrlForProtocol(protocol: string | undefined): string {
  return protocol === "https:" ? "/discovery" : localDiscoveryUrl;
}

async function readNextStreamEntry(stream: StreamHandle): Promise<unknown | null> {
  for (let i = 0; i < 4; i += 1) {
    const message = await stream.nextMessage();
    if (message == null) {
      return null;
    }
    if (isEntryMessage(message)) {
      return message;
    }
  }
  return null;
}

function isEntryMessage(message: unknown): boolean {
  return typeof message === "object" && message !== null && "entry" in message;
}

function stopTileSubscription(subscriptions: Map<string, TileSubscription>, tile: StageTileSpec) {
  const key = tileKey(tile);
  const subscription = subscriptions.get(key);
  if (subscription == null) {
    return;
  }
  subscription.cancelled = true;
  void subscription.stream?.close?.();
  subscriptions.delete(key);
}

function stopAllSubscriptions(subscriptions: Map<string, TileSubscription>) {
  for (const subscription of subscriptions.values()) {
    subscription.cancelled = true;
    void subscription.stream?.close?.();
  }
  subscriptions.clear();
}

function StatusChip({ label, value }: { label: string; value: string }) {
  return (
    <span className="rounded-control border border-line bg-panel px-2 py-1 text-slate-300">
      {label}: <span className="font-mono text-slate-100">{value}</span>
    </span>
  );
}

function statusClass(status: "idle" | "joining" | "joined" | "error"): string {
  const base = "rounded-control border px-2 py-1";
  if (status === "joined") {
    return `${base} border-emerald-800 bg-emerald-950/40 text-emerald-200`;
  }
  if (status === "error") {
    return `${base} border-red-900 bg-red-950/40 text-red-200`;
  }
  if (status === "joining") {
    return `${base} border-amber-800 bg-amber-950/40 text-amber-200`;
  }
  return `${base} border-line bg-panel text-slate-300`;
}

function sameTile(a: StageTileSpec, b: StageTileSpec): boolean {
  return a.peerId === b.peerId && a.sensorId === b.sensorId;
}

function tileKey(tile: StageTileSpec): string {
  return `${tile.peerId}:${tile.sensorId}`;
}
