import type { SensorSource, SensorSummary } from "./contract";

export const demoCameraSensor: SensorSummary = {
  sensor_id: "overwatch/browser/demo-camera",
  sensor_hash: "overwatch-demo-camera-v1",
  kind: "camera",
  label: "Browser preview",
};

export const generatedBytesSensor: SensorSummary = {
  sensor_id: "overwatch/browser/generated-bytes",
  sensor_hash: "overwatch-generated-bytes-v1",
  kind: "detection",
  label: "Generated bytes",
};

export const localDemoSensors = [demoCameraSensor, generatedBytesSensor];

const jpegFrames = [
  // 1x1 white JPEG.
  [
    255, 216, 255, 224, 0, 16, 74, 70, 73, 70, 0, 1, 1, 1, 0, 72, 0, 72, 0, 0,
    255, 219, 0, 67, 0, 3, 2, 2, 3, 2, 2, 3, 3, 3, 3, 4, 3, 3, 4, 5, 8, 5,
    5, 4, 4, 5, 10, 7, 7, 6, 8, 12, 10, 12, 12, 11, 10, 11, 11, 13, 14, 18,
    16, 13, 14, 17, 14, 11, 11, 16, 22, 16, 17, 19, 20, 21, 21, 21, 12, 15,
    23, 24, 22, 20, 24, 18, 20, 21, 20, 255, 192, 0, 11, 8, 0, 1, 0, 1, 1, 1,
    17, 0, 255, 196, 0, 20, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 7, 255, 196, 0, 20, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 255, 218, 0, 8, 1, 1, 0, 0, 63, 0, 213, 255, 217,
  ],
];

export function createDemoCameraSource(): AsyncIterable<{ seq: number; timestamp_ns: number; payload: number[] }> {
  return loopFrames(jpegFrames, 125);
}

export const generatedBytesSource: SensorSource = {
  kind: "generated-bytes",
  frames: [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
  ],
  interval_ms: 250,
};

async function* loopFrames(frames: number[][], intervalMs: number) {
  let seq = 0;
  while (true) {
    const payload = frames[seq % frames.length]!;
    yield {
      seq,
      timestamp_ns: Math.trunc(performance.now() * 1_000_000),
      payload,
    };
    seq += 1;
    await sleep(intervalMs);
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => window.setTimeout(resolve, ms));
}
