import { assertChapter, chapter, openDetails, reveal, selectDomain, assertLocalFonts, assertUsable, unexpectedConsoleError } from './guided-ui.mjs';
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdir, readFile } from 'node:fs/promises';
import { startFixture, DOMAIN, OTHER, RECORD, TEXT, LARGE, OVERSIZE } from './fixture.mjs';
const fixture = await startFixture();
const vite = spawn(process.execPath, ['node_modules/vite/bin/vite.js', 'preview', '--host', '127.0.0.1', '--port', '18116', '--strictPort'], { stdio: 'pipe' });
let browser;
const artifacts = new URL('../test-artifacts/', import.meta.url);
await mkdir(artifacts, { recursive: true });
try {
  for (let i = 0; i < 50; i++) { try { if ((await fetch('http://127.0.0.1:18116')).ok) break; } catch {} await new Promise(resolve => setTimeout(resolve, 100)); }
  browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1080 }, acceptDownloads: true, serviceWorkers: 'block' });
  const forbidden = [], logs = [], errors = [], consoleErrors = [];
  await context.route('**/*', route => {
    const url = new URL(route.request().url());
    if (!['127.0.0.1', 'localhost', '[::1]'].includes(url.hostname)) { forbidden.push(url.origin); return route.abort(); }
    return route.continue();
  });
  const page = await context.newPage();
  page.setDefaultTimeout(7000);
  page.setDefaultNavigationTimeout(10000);
  page.on('console', message => { logs.push(message.text()); if (unexpectedConsoleError(message)) consoleErrors.push(message.text()); });
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:18116');
  await assertLocalFonts(page);
  assert.equal(await page.locator('#connection-settings').evaluate(el => el.open), false);
  await openDetails(page, '#connection-settings');
  for (const id of ['api', 'dds', 'dms']) await page.locator('#' + id).fill(fixture.base);
  await assertUsable(page, ['#email', '#password', '#signin']);
  assert.equal(fixture.state.requests.length, 0, 'no login or service access on page load');
  await page.screenshot({ path: new URL('signed-out.png', artifacts).pathname, fullPage: true });
  const signIn = async () => {
    await page.locator('#email').fill('fixture@example.test');
    await page.locator('#password').fill('synthetic-password');
    await page.locator('#signin').click();
  };
  const contains = async (selector, value) => { await page.waitForFunction(({ selector, value }) => document.querySelector(selector)?.textContent.includes(value), { selector, value }); await reveal(page, selector); };
  fixture.state.denyLogin = true; await signIn(); await contains('#login-status', 'Sign-in failed');
  assert.equal(await page.locator('#password').inputValue(), '');
  fixture.state.denyLogin = false; await signIn(); await contains('#domains', 'Synthetic lab');
  await assertChapter(page, 'overview');
  assert.ok(await page.locator('#domain-controls').evaluate(el => el.open));
  await chapter(page, 'networking', true);
  assert.equal(await page.locator('#net-start').isEnabled(), false, 'Domain required before startup');
  assert.equal(await page.locator('#net-send').isEnabled(), false);
  await chapter(page, 'overview');
  await page.locator('#next').click(); await contains('#domains', 'Empty lab');
  assert.ok(fixture.state.requests.some(path => path.includes('offset=10')));
  await page.locator('#previous').click(); await contains('#domains', 'Synthetic lab');
  await page.getByRole('button', { name: /Synthetic lab/ }).click();
  await contains('#records', 'Lab sample');
  const selected = await page.locator('#selected').innerText();
  await chapter(page, 'networking', true);
  assert.equal(await page.locator('#selected').innerText(), selected);
  assert.equal(await page.locator('#net-state').innerText(), 'stopped');
  assert.equal(await page.locator('#net-start').isEnabled(), true);
  assert.equal(await page.locator('#net-send').isEnabled(), false);
  assert.equal(await page.locator('#net-results').innerText(), '');
  await contains('#portals', 'Lab portal'); await contains('#poses', '"px": 1');
  await chapter(page, 'data', true);
  for (const id of ['preview', 'download', 'copy-record']) assert.equal(await page.locator('#' + id).isEnabled(), false);
  await page.locator('#records button').filter({ has: page.getByText('Lab sample', { exact: true }) }).click(); await contains('#record', RECORD);
  assert.equal(await page.locator('#records button[aria-pressed="true"]').count(), 1);
  assert.ok(!(await page.locator('#content').innerText()).includes('Select a record.'));
  await page.locator('#preview').click(); await contains('#content', '[redacted]');
  assert.equal(await page.locator('#content img').count(), 0);
  assert.ok(!(await page.locator('#content').innerText()).includes('synthetic-secret'));
  assert.ok(!(await page.locator('#content').innerText()).includes('SYNTHETIC_'));
  await contains('#content', 'Useful fixture text');
  const downloadPending = page.waitForEvent('download'); await page.locator('#download').click();
  const download = await downloadPending;
  assert.equal(download.suggestedFilename(), `${RECORD}.bin`);
  assert.equal(await readFile(await download.path(), 'utf8'), fixture.content);
  await page.locator('#records button').filter({ has: page.getByText('Bearer [redacted]', { exact: true }) }).click(); await contains('#record', TEXT);
  await page.locator('#preview').click(); await contains('#content', 'Useful fixture text');
  assert.ok((await page.locator('#content').innerText()).includes('[redacted]'));
  assert.ok(!(await page.locator('#content').innerText()).includes('SYNTHETIC_'));
  for (const [id, name, expected] of [[LARGE, 'Large JSON', 'Truncated to 64 KiB.'], [OVERSIZE, 'Oversized text', 'Limit exceeded — buffered reads allow 8 MiB.']]) {
    await page.locator('#records button').filter({ has: page.getByText(name, { exact: true }) }).click(); await contains('#record', id);
    await page.locator('#preview').click();
    try { await contains('#content', expected); } catch (error) {
      const status = await page.locator('#content').innerText();
      console.error('Size case failed:', name, ['Loading…', 'Error — request failed. Check configuration and permissions, then retry.', 'Limit exceeded — buffered reads allow 8 MiB.'].includes(status) ? status : 'Unexpected preview content');
      throw error;
    }
    const preview = await page.locator('#content').innerText();
    assert.ok(Buffer.byteLength(preview) <= 65536);
    assert.ok(!preview.includes('SYNTHETIC_'));
  }
  await page.screenshot({ path: new URL('domain-data.png', artifacts).pathname, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await assertUsable(page, ['#name', '#preview', '#download', '#record-jump']);
  await page.locator('#record-jump').click();
  assert.ok(await page.locator('#record-detail').evaluate(el => el === document.activeElement));
  await chapter(page, 'networking');
  await assertUsable(page, ['#net-start', '[data-view="overview"]']);
  await page.screenshot({ path: new URL('networking-mobile.png', artifacts).pathname, fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1080 });
  await chapter(page, 'data');
  await page.locator('#name').fill('missing'); await page.locator('#filters button').click(); await contains('#data-status', 'Empty');
  assert.equal(await page.locator('#record').innerText(), '');
  await page.locator('#name').fill('Lab sample'); await openDetails(page, '#advanced-filters'); await page.locator('#type').fill('fixture.v1'); await page.locator('#ids').fill(RECORD);
  await page.locator('#filters button').click(); await contains('#records', 'Lab sample');
  fixture.state.denyPortals = true; await reveal(page, '#refresh-selected'); await page.locator('#refresh-selected').click();
  await contains('#portals', 'Denied'); await contains('#records', 'Lab sample'); await contains('#poses', '"px": 1');
  fixture.state.denyData = true; await reveal(page, '#refresh-selected'); await page.locator('#refresh-selected').click(); await contains('#data-status', 'Denied');
  assert.ok(!(await page.locator('body').innerText()).includes('synthetic-backend-secret'));
  fixture.state.denyData = false; fixture.state.denyPortals = false;
  fixture.state.denyDomains = true; await reveal(page, '#refresh-domains'); await page.locator('#refresh-domains').click(); await contains('#domain-status', 'Denied');
  assert.equal(await page.locator('#page').innerText(), '', 'failed page clears prior pagination');
  await selectDomain(page, DOMAIN); await contains('#records', 'Lab sample');
  fixture.state.denyDomains = false;
  fixture.state.emptyDomains = true; await reveal(page, '#refresh-domains'); await page.locator('#refresh-domains').click(); await contains('#domain-status', 'Empty');
  assert.equal(await page.locator('#page').innerText(), '0–0 / 0');
  fixture.state.emptyDomains = false; await reveal(page, '#refresh-domains'); await page.locator('#refresh-domains').click(); await contains('#domains', 'Synthetic lab');
  const select = id => selectDomain(page, id);
  await select(OTHER);
  await contains('#portals', 'Empty'); await contains('#poses', 'Empty'); await contains('#data-status', 'Empty');
  assert.equal(await page.locator('#records button').count(), 0);
  await select(DOMAIN); await contains('#records', 'Lab sample');
  const heldSince = (start, id) => fixture.state.exchanges.slice(start).filter(e => e.held && e.path.includes(id));
  const pendingReads = async (start, id) => {
    await fixture.waitFor(() => heldSince(start, id).length >= 2);
    const reads = heldSince(start, id);
    assert.ok(reads.every(e => !e.finished && !e.aborted));
    return reads;
  };
  const assertAborted = async reads => {
    await fixture.waitFor(() => reads.every(e => e.aborted));
    assert.ok(reads.every(e => !e.finished), 'server observed abort before any held response completed');
  };
  // Keep responses held throughout A -> B -> A; only cancellation can end them.
  fixture.state.holdReads = true;
  let start = fixture.state.exchanges.length;
  await reveal(page, '#refresh-selected'); await page.locator('#refresh-selected').click();
  const firstA = await pendingReads(start, DOMAIN);
  for (const view of ['data', 'networking', 'overview']) await chapter(page, view);
  assert.ok(firstA.every(e => !e.aborted && !e.finished), 'chapter switching preserves active reads');
  start = fixture.state.exchanges.length; await select(OTHER);
  await assertAborted(firstA);
  const pendingB = await pendingReads(start, OTHER);
  start = fixture.state.exchanges.length; await select(DOMAIN);
  await assertAborted(pendingB);
  const secondA = await pendingReads(start, DOMAIN);
  await reveal(page, '#metadata');
  assert.ok((await page.locator('#metadata').innerText()).includes(DOMAIN));
  fixture.releaseReads();
  await contains('#records', 'Lab sample');
  await fixture.waitFor(() => secondA.every(e => e.finished));
  fixture.state.holdReads = true; start = fixture.state.exchanges.length;
  await reveal(page, '#refresh-selected'); await page.locator('#refresh-selected').click();
  const logoutReads = await pendingReads(start, DOMAIN);
  await page.locator('#logout').click(); await contains('#session-status', 'Signed out');
  await assertAborted(logoutReads);
  assert.equal(await page.locator('#workspace').isVisible(), false);
  fixture.releaseReads();
  await signIn(); await contains('#domains', 'Synthetic lab');
  await select(DOMAIN); await contains('#records', 'Lab sample');
  await page.locator('#logout').click(); await contains('#session-status', 'Signed out');
  // Login has no AbortSignal; release its late response after cancellation.
  fixture.state.holdLogin = true; start = fixture.state.exchanges.length;
  await signIn();
  await fixture.waitFor(() => fixture.state.exchanges.slice(start).some(e => e.path === '/user/login' && e.held));
  const lateLogin = fixture.state.exchanges.slice(start).find(e => e.path === '/user/login');
  await page.locator('#logout').click(); await contains('#session-status', 'Signed out');
  const lateResponse = page.waitForResponse(response => response.url().endsWith('/user/login'));
  fixture.state.holdLogin = false; lateLogin.release();
  await (await lateResponse).finished();
  assert.equal(await page.locator('#workspace').isVisible(), false);
  await signIn(); await contains('#domains', 'Synthetic lab');
  await select(DOMAIN); await contains('#records', 'Lab sample');
  await page.locator('#logout').click(); await contains('#session-status', 'Signed out');
  assert.ok(fixture.state.aborted >= firstA.length + pendingB.length + logoutReads.length);
  const storage = await page.evaluate(() => ({ local: { ...localStorage }, session: { ...sessionStorage } }));
  assert.deepEqual(Object.keys(storage.local), ['core-explorer.client-id']); assert.deepEqual(storage.session, {});
  for (const secret of ['synthetic-password', 'synthetic-user', 'synthetic-refresh', 'synthetic-secret', 'synthetic-backend-secret']) assert.ok(!JSON.stringify(logs).includes(secret));
  assert.deepEqual(forbidden, []); assert.deepEqual(errors, []); assert.deepEqual(consoleErrors, []);
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: new URL('mobile.png', artifacts).pathname, fullPage: true });
  console.log('PASS real-WASM Chromium: login failure/success/cancellation, pagination/manual selection, metadata/portals/poses, filters, preview/download, empty/denied, server-observed A→B→A/logout aborts, repeated login recovery, 64 KiB preview/8 MiB read limits, empty page, storage/log isolation; no nonlocal requests.');
} finally {
  await browser?.close(); vite.kill('SIGTERM'); await fixture.close();
}
