# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: map.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class MapUpdate(betterproto.Message):
    """
    One append-only, mergeable change to a map. `timestamp_ns` is supplied by
    the log framing; this payload deliberately contains no peer identity, so it
    can be materialized and relayed by any peer.
    """

    voxel_chunks: List["VoxelChunkUpdate"] = betterproto.message_field(1)


@dataclass
class VoxelChunkUpdate(betterproto.Message):
    """
    A sparse update to one fixed-size chunk of a voxel map. The chunk
    coordinate is in map-grid chunk units; `voxels` use zero-based coordinates
    local to it.
    """

    chunk_x: int = betterproto.sint32_field(1)
    chunk_y: int = betterproto.sint32_field(2)
    chunk_z: int = betterproto.sint32_field(3)
    voxels: List["VoxelDelta"] = betterproto.message_field(4)


@dataclass
class VoxelDelta(betterproto.Message):
    """
    Evidence deltas are summed per voxel. Positive occupancy_delta means an
    observed surface; negative means traversed free space. Consumers must not
    clamp stored evidence, preserving deterministic replay and commutative
    merge.
    """

    x: int = betterproto.uint32_field(1)
    y: int = betterproto.uint32_field(2)
    z: int = betterproto.uint32_field(3)
    occupancy_delta: float = betterproto.float_field(4)
    semantics: List["SemanticDelta"] = betterproto.message_field(5)


@dataclass
class SemanticDelta(betterproto.Message):
    """
    Optional evidence for an application-defined semantic class. Class labels
    live in the Map Registry, not in individual updates.
    """

    class_id: int = betterproto.uint32_field(1)
    evidence_delta: float = betterproto.float_field(2)
