# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: point_cloud_stream.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PointCloudFrame(betterproto.Message):
    bytes: bytes = betterproto.bytes_field(1)
