# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: point_cloud.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PointCloudLogEntry(betterproto.Message):
    data: bytes = betterproto.bytes_field(1)
