# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: scalar.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Data(betterproto.Message):
    value: float = betterproto.double_field(1)
